version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "enhancement"
  - package-ecosystem: "nuget"
    directory: "/.config"
    schedule:
      interval: "weekly"
    labels:
      - "enhancement"
