namespace SwaggerProvider.Tests.RuntimeHelpersTests

open System
open System.IO
open System.Net
open System.Net.Http
open System.Text.Json
open System.Text.Json.Serialization
open System.Threading
open System.Threading.Tasks
open Xunit
open FsUnitTyped
open Swagger.Internal.RuntimeHelpers

/// Unit tests for RuntimeHelpers — the runtime parameter serialization and HTTP utilities.
/// These functions are used by every generated API client but previously had no dedicated tests.
module ToParamTests =

    [<Fact>]
    let ``toParam formats DateTime as ISO 8601 round-trip``() =
        let dt = DateTime(2024, 6, 15, 10, 30, 0, DateTimeKind.Utc)
        let result = toParam(box dt)
        result |> shouldEqual(dt.ToString("O"))

    [<Fact>]
    let ``toParam formats DateTimeOffset as ISO 8601 round-trip``() =
        let dto = DateTimeOffset(2024, 6, 15, 10, 30, 0, TimeSpan.FromHours(2.0))
        let result = toParam(box dto)
        result |> shouldEqual(dto.ToString("O"))

    [<Fact>]
    let ``toParam returns null for null input``() =
        let result = toParam null
        result |> shouldEqual null

    [<Fact>]
    let ``toParam uses ToString for integers``() =
        let result = toParam(box 42)
        result |> shouldEqual "42"

    [<Fact>]
    let ``toParam uses ToString for strings``() =
        let result = toParam(box "hello world")
        result |> shouldEqual "hello world"

    [<Fact>]
    let ``toParam uses ToString for Guid``() =
        let g = Guid("d3b07384-d9a2-4e3f-9a4b-1234567890ab")
        let result = toParam(box g)
        result |> shouldEqual(g.ToString())

    [<Fact>]
    let ``toParam unwraps Some(Guid) — fixes issue #140``() =
        let g = Guid("d3b07384-d9a2-4e3f-9a4b-1234567890ab")
        let result = toParam(box(Some g))
        result |> shouldEqual(g.ToString())

    [<Fact>]
    let ``toParam returns null for None(Guid) — fixes issue #140``() =
        let result = toParam(box(None: Guid option))
        result |> shouldEqual null

    [<Fact>]
    let ``toParam unwraps Some(string)``() =
        let result = toParam(box(Some "token-value"))
        result |> shouldEqual "token-value"

    [<Fact>]
    let ``toParam returns null for None(string)``() =
        let result = toParam(box(None: string option))
        result |> shouldEqual null

    [<Fact>]
    let ``toParam unwraps Some(DateTimeOffset) and formats as ISO 8601``() =
        let dto = DateTimeOffset(2024, 1, 15, 12, 0, 0, TimeSpan.Zero)
        let result = toParam(box(Some dto))
        result |> shouldEqual(dto.ToString("O"))

    [<Fact>]
    let ``toParam formats DateOnly as ISO 8601``() =
        let d = DateOnly(2025, 7, 4)
        let result = toParam(box d)
        result |> shouldEqual "2025-07-04"

    [<Fact>]
    let ``toParam unwraps Some(DateOnly) and formats as ISO 8601``() =
        let d = DateOnly(2025, 1, 31)
        let result = toParam(box(Some d))
        result |> shouldEqual "2025-01-31"

    [<Fact>]
    let ``toParam returns null for None(DateOnly)``() =
        let result = toParam(box(None: DateOnly option))
        result |> shouldEqual null

    [<Fact>]
    let ``toParam formats TimeOnly as HH:mm:ss.FFFFFFF``() =
        let t = TimeOnly(14, 30, 0)
        let result = toParam(box t)
        result |> shouldEqual "14:30:00"

    [<Fact>]
    let ``toParam formats TimeOnly with sub-second precision``() =
        let t = TimeOnly(9, 5, 3, 123)
        let result = toParam(box t)
        // "HH:mm:ss.FFFFFFF" — trailing zeros stripped by F specifier
        result |> shouldEqual "09:05:03.123"

    [<Fact>]
    let ``toParam unwraps Some(TimeOnly) and formats correctly``() =
        let t = TimeOnly(8, 0, 0)
        let result = toParam(box(Some t))
        result |> shouldEqual "08:00:00"

    [<Fact>]
    let ``toParam returns null for None(TimeOnly)``() =
        let result = toParam(box(None: TimeOnly option))
        result |> shouldEqual null


// ── CLI enum serialization via toParam ──────────────────────────────────────────────────────
// toParam must serialize string enums to their original OpenAPI wire values and integer
// enums to their underlying integer representation.
module EnumToParamTests =
    // String enum with the new JsonStringEnumMemberName attribute (STJ 9+).
    // This is what the type provider now emits for sanitised member names.
    [<JsonConverter(typeof<JsonStringEnumConverter>)>]
    type StringStatus =
        | [<JsonStringEnumMemberName("active")>] Active = 0
        | [<JsonStringEnumMemberName("inactive")>] Inactive = 1
        | [<JsonStringEnumMemberName("in-progress")>] InProgress = 2

    // Backward-compat: string enum using the legacy [JsonPropertyName] attribute.
    // buildEnumSerializer must still work for enums generated by older type-provider builds.
    [<JsonConverter(typeof<JsonStringEnumConverter>)>]
    type LegacyStringStatus =
        | [<JsonPropertyName("active")>] Active = 0
        | [<JsonPropertyName("inactive")>] Inactive = 1
        | [<JsonPropertyName("in-progress")>] InProgress = 2

    // Integer enum: no JSON attributes, serializes as the underlying integer.
    type IntStatus =
        | Pending = 1
        | Running = 2
        | Done = 3

    [<Fact>]
    let ``toParam serializes string enum to its wire value (exact case)``() =
        let result = toParam(box StringStatus.Active)
        result |> shouldEqual "active"

    [<Fact>]
    let ``toParam serializes string enum with hyphenated wire value``() =
        let result = toParam(box StringStatus.InProgress)
        result |> shouldEqual "in-progress"

    [<Fact>]
    let ``toParam serializes string enum inactive value``() =
        let result = toParam(box StringStatus.Inactive)
        result |> shouldEqual "inactive"

    [<Fact>]
    let ``toParam serializes integer enum to its underlying integer value``() =
        let result = toParam(box IntStatus.Pending)
        result |> shouldEqual "1"

    [<Fact>]
    let ``toParam serializes integer enum Running to 2``() =
        let result = toParam(box IntStatus.Running)
        result |> shouldEqual "2"

    [<Fact>]
    let ``toParam unwraps Some(string enum) and returns wire value``() =
        let result = toParam(box(Some StringStatus.Active))
        result |> shouldEqual "active"

    [<Fact>]
    let ``toParam returns null for None(string enum)``() =
        let result = toParam(box(None: StringStatus option))
        result |> shouldEqual null

    [<Fact>]
    let ``toParam unwraps Some(integer enum) and returns integer string``() =
        let result = toParam(box(Some IntStatus.Done))
        result |> shouldEqual "3"

    // Backward-compat tests: enums generated by older type-provider builds carry
    // [JsonPropertyName] instead of [JsonStringEnumMemberName]; they must still work.
    [<Fact>]
    let ``toParam serializes legacy JsonPropertyName string enum (backward compat)``() =
        let result = toParam(box LegacyStringStatus.InProgress)
        result |> shouldEqual "in-progress"

    [<Fact>]
    let ``toParam serializes legacy JsonPropertyName inactive (backward compat)``() =
        let result = toParam(box LegacyStringStatus.Inactive)
        result |> shouldEqual "inactive"


module ToQueryParamsTests =

    let private stubClient =
        { new Swagger.ProvidedApiClientBase(null, JsonSerializerOptions()) with
            override _.Serialize(v) =
                JsonSerializer.Serialize v

            override _.Deserialize(s, t) =
                JsonSerializer.Deserialize(s, t) }

    [<Fact>]
    let ``toQueryParams handles string array``() =
        let result = toQueryParams "tag" (box [| "alpha"; "beta"; "gamma" |]) stubClient

        result
        |> shouldEqual [ ("tag", "alpha"); ("tag", "beta"); ("tag", "gamma") ]

    [<Fact>]
    let ``toQueryParams handles int32 array``() =
        let result = toQueryParams "id" (box [| 1; 2; 3 |]) stubClient
        result |> shouldEqual [ ("id", "1"); ("id", "2"); ("id", "3") ]

    [<Fact>]
    let ``toQueryParams handles int64 array``() =
        let result = toQueryParams "id" (box [| 1L; 2L; 3L |]) stubClient
        result |> shouldEqual [ ("id", "1"); ("id", "2"); ("id", "3") ]

    [<Fact>]
    let ``toQueryParams handles bool array``() =
        let result = toQueryParams "flag" (box [| true; false |]) stubClient
        result |> shouldEqual [ ("flag", "True"); ("flag", "False") ]

    [<Fact>]
    let ``toQueryParams formats DateTime array as ISO 8601``() =
        let dt = DateTime(2024, 1, 15, 12, 0, 0, DateTimeKind.Utc)
        let result = toQueryParams "d" (box [| dt |]) stubClient
        result |> shouldHaveLength 1
        fst result[0] |> shouldEqual "d"
        snd result[0] |> shouldEqual(dt.ToString("O"))

    [<Fact>]
    let ``toQueryParams formats DateTimeOffset array as ISO 8601``() =
        let dto = DateTimeOffset(2024, 1, 15, 12, 0, 0, TimeSpan.Zero)
        let result = toQueryParams "d" (box [| dto |]) stubClient
        result |> shouldHaveLength 1
        snd result[0] |> shouldEqual(dto.ToString("O"))

    [<Fact>]
    let ``toQueryParams handles Option<string> Some``() =
        let result = toQueryParams "q" (box(Some "hello")) stubClient
        result |> shouldEqual [ ("q", "hello") ]

    [<Fact>]
    let ``toQueryParams handles Option<string> None``() =
        let result = toQueryParams "q" (box(Option<string>.None)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams handles Option<int32> Some``() =
        let result = toQueryParams "n" (box(Some 99)) stubClient
        result |> shouldEqual [ ("n", "99") ]

    [<Fact>]
    let ``toQueryParams handles Option<int32> None``() =
        let result = toQueryParams "n" (box(Option<int>.None)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams handles Option<DateTime> Some as ISO 8601``() =
        let dt = DateTime(2024, 3, 1, 0, 0, 0, DateTimeKind.Utc)
        let result = toQueryParams "d" (box(Some dt)) stubClient
        result |> shouldHaveLength 1
        snd result[0] |> shouldEqual(dt.ToString("O"))

    [<Fact>]
    let ``toQueryParams handles Option<DateTime> None``() =
        let result = toQueryParams "d" (box(Option<DateTime>.None)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams handles Option<Guid> Some``() =
        let g = Guid.NewGuid()
        let result = toQueryParams "id" (box(Some g)) stubClient
        result |> shouldEqual [ ("id", g.ToString()) ]

    [<Fact>]
    let ``toQueryParams handles plain DateTime as ISO 8601``() =
        let dt = DateTime(2024, 6, 1, 8, 0, 0, DateTimeKind.Utc)
        let result = toQueryParams "dt" (box dt) stubClient
        result |> shouldHaveLength 1
        snd result[0] |> shouldEqual(dt.ToString("O"))

    [<Fact>]
    let ``toQueryParams handles plain DateTimeOffset as ISO 8601``() =
        let dto = DateTimeOffset(2024, 6, 1, 8, 0, 0, TimeSpan.FromHours(-5.0))
        let result = toQueryParams "dto" (box dto) stubClient
        result |> shouldHaveLength 1
        snd result[0] |> shouldEqual(dto.ToString("O"))

    [<Fact>]
    let ``toQueryParams handles plain string``() =
        let result = toQueryParams "q" (box "search term") stubClient
        result |> shouldEqual [ ("q", "search term") ]

    [<Fact>]
    let ``toQueryParams returns empty list for null input (treated as Option None)``() =
        // In F#, None for any option type is compiled as null at the .NET level,
        // so a null obj is treated as Option None and returns an empty list.
        let result = toQueryParams "q" null stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams skips None items in Option array``() =
        let values: Option<int>[] = [| Some 1; None; Some 3 |]
        let result = toQueryParams "n" (box values) stubClient
        result |> shouldEqual [ ("n", "1"); ("n", "3") ]

    [<Fact>]
    let ``toQueryParams handles Guid array``() =
        let g1 = Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
        let g2 = Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
        let result = toQueryParams "id" (box [| g1; g2 |]) stubClient
        result |> shouldEqual [ ("id", g1.ToString()); ("id", g2.ToString()) ]

    [<Fact>]
    let ``toQueryParams skips None items in Option<Guid> array``() =
        let g = Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
        let values: Option<Guid>[] = [| Some g; None |]
        let result = toQueryParams "id" (box values) stubClient
        result |> shouldEqual [ ("id", g.ToString()) ]

    [<Fact>]
    let ``toQueryParams handles float32 array``() =
        let result = toQueryParams "v" (box [| 1.5f; 2.5f |]) stubClient
        result |> shouldEqual [ ("v", "1.5"); ("v", "2.5") ]

    [<Fact>]
    let ``toQueryParams handles double array``() =
        let result = toQueryParams "v" (box [| 1.5; 2.5 |]) stubClient
        result |> shouldEqual [ ("v", "1.5"); ("v", "2.5") ]

    [<Fact>]
    let ``toQueryParams handles byte array as base64``() =
        // byte[] is serialized via client.Serialize (JSON base64) with surrounding quotes trimmed
        let bytes = [| 72uy; 101uy; 108uy; 108uy; 111uy |] // "Hello" in ASCII
        let expected = (JsonSerializer.Serialize bytes).Trim('"')
        let result = toQueryParams "data" (box bytes) stubClient
        result |> shouldEqual [ ("data", expected) ]

    [<Fact>]
    let ``toQueryParams skips None items in Option<string> array``() =
        let values: Option<string>[] = [| Some "a"; None; Some "c" |]
        let result = toQueryParams "q" (box values) stubClient
        result |> shouldEqual [ ("q", "a"); ("q", "c") ]

    [<Fact>]
    let ``toQueryParams skips None items in Option<float32> array``() =
        let values: Option<float32>[] = [| Some 1.5f; None; Some 3.5f |]
        let result = toQueryParams "v" (box values) stubClient
        result |> shouldEqual [ ("v", "1.5"); ("v", "3.5") ]

    [<Fact>]
    let ``toQueryParams skips None items in Option<double> array``() =
        let values: Option<double>[] = [| Some 1.5; None; Some 3.5 |]
        let result = toQueryParams "v" (box values) stubClient
        result |> shouldEqual [ ("v", "1.5"); ("v", "3.5") ]

    [<Fact>]
    let ``toQueryParams handles Option<bool> Some``() =
        let result = toQueryParams "flag" (box(Some true)) stubClient
        result |> shouldEqual [ ("flag", "True") ]

    [<Fact>]
    let ``toQueryParams handles Option<bool> None``() =
        let result = toQueryParams "flag" (box(None: bool option)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams handles Option<int64> Some``() =
        let result = toQueryParams "id" (box(Some 9876543210L)) stubClient
        result |> shouldEqual [ ("id", "9876543210") ]

    [<Fact>]
    let ``toQueryParams handles Option<int64> None``() =
        let result = toQueryParams "id" (box(None: int64 option)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams handles Option<float32> Some``() =
        let result = toQueryParams "rate" (box(Some 3.14f)) stubClient
        result |> shouldEqual [ ("rate", "3.14") ]

    [<Fact>]
    let ``toQueryParams handles Option<float32> None``() =
        let result = toQueryParams "rate" (box(None: float32 option)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams handles Option<double> Some``() =
        let result = toQueryParams "rate" (box(Some 2.718)) stubClient
        result |> shouldEqual [ ("rate", "2.718") ]

    [<Fact>]
    let ``toQueryParams handles Option<double> None``() =
        let result = toQueryParams "rate" (box(None: double option)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams handles Option<DateTimeOffset> Some``() =
        let dto = DateTimeOffset(2025, 3, 15, 9, 0, 0, TimeSpan.Zero)
        let result = toQueryParams "since" (box(Some dto)) stubClient
        result |> shouldEqual [ ("since", dto.ToString("O")) ]

    [<Fact>]
    let ``toQueryParams handles Option<DateTimeOffset> None``() =
        let result = toQueryParams "since" (box(None: DateTimeOffset option)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams skips None items in Option<DateTimeOffset> array``() =
        let dto = DateTimeOffset(2025, 6, 1, 0, 0, 0, TimeSpan.Zero)
        let values: Option<DateTimeOffset>[] = [| Some dto; None |]
        let result = toQueryParams "ts" (box values) stubClient
        result |> shouldEqual [ ("ts", dto.ToString("O")) ]

    [<Fact>]
    let ``toQueryParams handles DateOnly as ISO 8601``() =
        let d = DateOnly(2025, 7, 4)
        let result = toQueryParams "date" (box d) stubClient
        result |> shouldEqual [ ("date", "2025-07-04") ]

    [<Fact>]
    let ``toQueryParams handles DateOnly array``() =
        let values: DateOnly[] = [| DateOnly(2025, 1, 1); DateOnly(2025, 12, 31) |]
        let result = toQueryParams "dates" (box values) stubClient

        result
        |> shouldEqual [ ("dates", "2025-01-01"); ("dates", "2025-12-31") ]

    [<Fact>]
    let ``toQueryParams handles Option<DateOnly> Some``() =
        let d = DateOnly(2025, 6, 15)
        let result = toQueryParams "date" (box(Some d)) stubClient
        result |> shouldEqual [ ("date", "2025-06-15") ]

    [<Fact>]
    let ``toQueryParams handles Option<DateOnly> None``() =
        let result = toQueryParams "date" (box(None: DateOnly option)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams skips None items in Option<DateOnly> array``() =
        let d = DateOnly(2025, 3, 1)
        let values: Option<DateOnly>[] = [| Some d; None |]
        let result = toQueryParams "dates" (box values) stubClient
        result |> shouldEqual [ ("dates", "2025-03-01") ]

    [<Fact>]
    let ``toQueryParams handles TimeOnly``() =
        let t = TimeOnly(14, 30, 0)
        let result = toQueryParams "time" (box t) stubClient
        result |> shouldEqual [ ("time", "14:30:00") ]

    [<Fact>]
    let ``toQueryParams handles TimeOnly array``() =
        let values: TimeOnly[] = [| TimeOnly(9, 0, 0); TimeOnly(17, 30, 0) |]
        let result = toQueryParams "times" (box values) stubClient
        result |> shouldEqual [ ("times", "09:00:00"); ("times", "17:30:00") ]

    [<Fact>]
    let ``toQueryParams handles Option<TimeOnly> Some``() =
        let t = TimeOnly(12, 0, 0)
        let result = toQueryParams "time" (box(Some t)) stubClient
        result |> shouldEqual [ ("time", "12:00:00") ]

    [<Fact>]
    let ``toQueryParams handles Option<TimeOnly> None``() =
        let result = toQueryParams "time" (box(None: TimeOnly option)) stubClient
        result |> shouldEqual []

    [<Fact>]
    let ``toQueryParams skips None items in Option<TimeOnly> array``() =
        let t = TimeOnly(8, 0, 0)
        let values: Option<TimeOnly>[] = [| Some t; None |]
        let result = toQueryParams "times" (box values) stubClient
        result |> shouldEqual [ ("times", "08:00:00") ]


module CombineUrlTests =

    [<Fact>]
    let ``combineUrl joins paths without extra slashes``() =
        combineUrl "http://example.com/api" "v1/users"
        |> shouldEqual "http://example.com/api/v1/users"

    [<Fact>]
    let ``combineUrl trims trailing slash from left``() =
        combineUrl "http://example.com/api/" "v1/users"
        |> shouldEqual "http://example.com/api/v1/users"

    [<Fact>]
    let ``combineUrl trims leading slash from right``() =
        combineUrl "http://example.com/api" "/v1/users"
        |> shouldEqual "http://example.com/api/v1/users"

    [<Fact>]
    let ``combineUrl trims both slashes``() =
        combineUrl "http://example.com/api/" "/v1/users"
        |> shouldEqual "http://example.com/api/v1/users"

    [<Fact>]
    let ``combineUrl works with empty path segment``() =
        combineUrl "http://example.com" ""
        |> shouldEqual "http://example.com/"


module CreateHttpRequestTests =

    [<Fact>]
    let ``createHttpRequest creates GET request``() =
        use req = createHttpRequest "GET" "v1/users" []
        req.Method |> shouldEqual HttpMethod.Get

    [<Fact>]
    let ``createHttpRequest creates POST request``() =
        use req = createHttpRequest "POST" "v1/users" []
        req.Method |> shouldEqual HttpMethod.Post

    [<Fact>]
    let ``createHttpRequest creates DELETE request``() =
        use req = createHttpRequest "DELETE" "v1/users/42" []
        req.Method |> shouldEqual HttpMethod.Delete

    [<Fact>]
    let ``createHttpRequest is case-insensitive for method``() =
        use req = createHttpRequest "get" "v1/users" []
        req.Method |> shouldEqual HttpMethod.Get

    [<Fact>]
    let ``createHttpRequest appends query parameters``() =
        use req = createHttpRequest "GET" "v1/users" [ ("page", "2"); ("size", "10") ]
        let uri = req.RequestUri.ToString()
        uri |> shouldContainText "page=2"
        uri |> shouldContainText "size=10"

    [<Fact>]
    let ``createHttpRequest skips null query parameter values``() =
        use req = createHttpRequest "GET" "v1/users" [ ("q", null) ]
        let uri = req.RequestUri.ToString()
        uri |> shouldNotContainText "q="

    [<Fact>]
    let ``createHttpRequest includes path in request URI``() =
        use req = createHttpRequest "GET" "v1/pets/42" []
        req.RequestUri.ToString() |> shouldContainText "v1/pets/42"


module FillHeadersTests =

    [<Fact>]
    let ``fillHeaders adds standard headers``() =
        use req = new HttpRequestMessage(HttpMethod.Get, "http://example.com/")
        fillHeaders req [ ("Accept", "application/json"); ("X-Api-Key", "secret") ]
        req.Headers.Contains("Accept") |> shouldEqual true
        req.Headers.Contains("X-Api-Key") |> shouldEqual true

    [<Fact>]
    let ``fillHeaders skips null-value headers``() =
        use req = new HttpRequestMessage(HttpMethod.Get, "http://example.com/")
        fillHeaders req [ ("X-Missing", null) ]
        req.Headers.Contains("X-Missing") |> shouldEqual false

    [<Fact>]
    let ``fillHeaders silently ignores Content-Type header``() =
        // Content-Type must be set on HttpContent, not on the request; this should not throw
        use req = new HttpRequestMessage(HttpMethod.Get, "http://example.com/")
        // Should not raise an exception even though Content-Type cannot be added to request headers
        fillHeaders req [ ("Content-Type", "application/json") ]


module ToContentTests =

    [<Fact>]
    let ``toStringContent returns JSON content type``() =
        use c = toStringContent "{\"key\":\"value\"}"
        c.Headers.ContentType.MediaType |> shouldEqual "application/json"

    [<Fact>]
    let ``toStringContent preserves the body``() =
        let body = "{\"name\":\"Alice\"}"
        use c = toStringContent body
        let text = c.ReadAsStringAsync() |> Async.AwaitTask |> Async.RunSynchronously
        text |> shouldEqual body

    [<Fact>]
    let ``toTextContent returns text/plain content type``() =
        use c = toTextContent "hello"
        c.Headers.ContentType.MediaType |> shouldEqual "text/plain"

    [<Fact>]
    let ``toStreamContent sets provided content type``() =
        use stream = new MemoryStream([| 1uy; 2uy; 3uy |])
        use c = toStreamContent(box stream, "application/octet-stream")

        c.Headers.ContentType.MediaType
        |> shouldEqual "application/octet-stream"

    [<Fact>]
    let ``toStreamContent omits content type when empty``() =
        use stream = new MemoryStream([| 1uy; 2uy |])
        use c = toStreamContent(box stream, "")
        c.Headers.ContentType |> shouldEqual null

    [<Fact>]
    let ``toStreamContent throws for non-stream input``() =
        Assert.Throws<Exception>(fun () -> toStreamContent(box "not a stream", "application/json") |> ignore)
        |> ignore


/// A stub HttpMessageHandler that always returns a fixed status code and body.
type private StubHttpMessageHandler(statusCode: HttpStatusCode, responseBody: string) =
    inherit HttpMessageHandler()

    override _.SendAsync(_request: HttpRequestMessage, cancellationToken: CancellationToken) =
        cancellationToken.ThrowIfCancellationRequested()
        let response = new HttpResponseMessage(statusCode)
        response.Content <- new StringContent(responseBody)
        Task.FromResult(response)


module OpenApiExceptionTests =

    let private makeClient(handler: HttpMessageHandler) =
        let httpClient = new HttpClient(handler)
        httpClient.BaseAddress <- Uri("http://stub/")

        { new Swagger.ProvidedApiClientBase(httpClient, JsonSerializerOptions()) with
            override _.Serialize(v) =
                JsonSerializer.Serialize v

            override _.Deserialize(s, t) =
                JsonSerializer.Deserialize(s, t) }

    [<Fact>]
    let ``OpenApiException message includes description when no body``() =
        use content = new StringContent("")
        use response = new HttpResponseMessage(HttpStatusCode.NotFound)
        let ex = Swagger.OpenApiException(404, "Not Found", response.Headers, content)
        ex.Message |> shouldEqual "Not Found"

    [<Fact>]
    let ``OpenApiException message includes body when body is provided``() =
        use content = new StringContent("{\"error\":\"missing\"}")
        use response = new HttpResponseMessage(HttpStatusCode.NotFound)

        let ex =
            Swagger.OpenApiException(404, "Not Found", response.Headers, content, "{\"error\":\"missing\"}")

        ex.Message |> shouldContainText "Not Found"
        ex.Message |> shouldContainText "{\"error\":\"missing\"}"

    [<Fact>]
    let ``OpenApiException ResponseBody is empty string when not provided``() =
        use content = new StringContent("")
        use response = new HttpResponseMessage(HttpStatusCode.BadRequest)
        let ex = Swagger.OpenApiException(400, "Bad Request", response.Headers, content)
        ex.ResponseBody |> shouldEqual ""

    [<Fact>]
    let ``OpenApiException ResponseBody returns the provided body``() =
        use content = new StringContent("error detail")
        use response = new HttpResponseMessage(HttpStatusCode.UnprocessableEntity)

        let ex =
            Swagger.OpenApiException(422, "Unprocessable Entity", response.Headers, content, "error detail")

        ex.ResponseBody |> shouldEqual "error detail"

    [<Fact>]
    let ``OpenApiException message is only description when body is empty string``() =
        use content = new StringContent("")
        use response = new HttpResponseMessage(HttpStatusCode.Forbidden)
        let ex = Swagger.OpenApiException(403, "Forbidden", response.Headers, content, "")
        ex.Message |> shouldEqual "Forbidden"

    [<Fact>]
    let ``CallAsync raises OpenApiException with response body for documented error code``() =
        task {
            let expectedBody = "{\"message\":\"pet not found\"}"

            use handler = new StubHttpMessageHandler(HttpStatusCode.NotFound, expectedBody)
            let client = makeClient handler

            use request = new HttpRequestMessage(HttpMethod.Get, "http://stub/pets/1")

            let! ex =
                Assert.ThrowsAsync<Swagger.OpenApiException>(fun () ->
                    task {
                        let! _ = client.CallAsync(request, [| "404" |], [| "Pet not found" |], CancellationToken.None)
                        ()
                    })

            ex.StatusCode |> shouldEqual 404
            ex.ResponseBody |> shouldEqual expectedBody
            ex.Message |> shouldContainText "Pet not found"
            ex.Message |> shouldContainText expectedBody
        }

    [<Fact>]
    let ``CallAsync raises OpenApiException without body text when body is empty``() =
        task {
            use handler = new StubHttpMessageHandler(HttpStatusCode.NotFound, "")
            let client = makeClient handler

            use request = new HttpRequestMessage(HttpMethod.Get, "http://stub/pets/1")

            let! ex =
                Assert.ThrowsAsync<Swagger.OpenApiException>(fun () ->
                    task {
                        let! _ = client.CallAsync(request, [| "404" |], [| "Pet not found" |], CancellationToken.None)
                        ()
                    })

            ex.StatusCode |> shouldEqual 404
            ex.Message |> shouldEqual "Pet not found"
        }

    [<Fact>]
    let ``CallAsync raises OpenApiException for undocumented error code``() =
        task {
            use handler =
                new StubHttpMessageHandler(HttpStatusCode.InternalServerError, "server error")

            let client = makeClient handler

            use request = new HttpRequestMessage(HttpMethod.Get, "http://stub/pets/1")

            // 500 is not in the documented error codes; OpenApiException should be raised with response body
            let! ex =
                Assert.ThrowsAsync<Swagger.OpenApiException>(fun () ->
                    task {
                        let! _ = client.CallAsync(request, [| "404" |], [| "Pet not found" |], CancellationToken.None)
                        ()
                    })

            ex.StatusCode |> shouldEqual 500
            ex.ResponseBody |> shouldEqual "server error"
        }

    [<Fact>]
    let ``CallAsync with CancellationToken returns content on success``() =
        task {
            use handler = new StubHttpMessageHandler(HttpStatusCode.OK, "result")
            let client = makeClient handler
            use request = new HttpRequestMessage(HttpMethod.Get, "http://stub/pets/1")
            use! response = client.CallAsync(request, [||], [||], CancellationToken.None)
            let! body = response.Content.ReadAsStringAsync()
            body |> shouldEqual "result"
        }

    [<Fact>]
    let ``CallAsync with already-cancelled token raises OperationCanceledException``() =
        task {
            use cts = new CancellationTokenSource()
            cts.Cancel()

            use handler = new StubHttpMessageHandler(HttpStatusCode.OK, "ok")
            let client = makeClient handler
            use request = new HttpRequestMessage(HttpMethod.Get, "http://stub/pets/1")

            let! _ =
                Assert.ThrowsAnyAsync<OperationCanceledException>(fun () ->
                    task {
                        let! _ = client.CallAsync(request, [||], [||], cts.Token)
                        ()
                    })

            ()
        }

/// Test types for formatObject tests — must be plain .NET classes with declared public properties.
type FmtSingle(name: string) =
    member _.Name = name

type FmtInt(count: int) =
    member _.Count = count

type FmtNullable(label: string) =
    member _.Label: string = label

type FmtMulti(age: int, name: string) =
    member _.Age = age
    member _.Name = name

type FmtArray(tags: string[]) =
    member _.Tags = tags


module FormatObjectTests =

    [<Fact>]
    let ``formatObject formats string property with quotes``() =
        let obj = FmtSingle("Alice")
        formatObject obj |> shouldEqual "{Name=\"Alice\"}"

    [<Fact>]
    let ``formatObject formats integer property without quotes``() =
        let obj = FmtInt(42)
        formatObject obj |> shouldEqual "{Count=42}"

    [<Fact>]
    let ``formatObject formats null string property as null``() =
        let obj = FmtNullable(null)
        formatObject obj |> shouldEqual "{Label=null}"

    [<Fact>]
    let ``formatObject formats array property as bracketed list``() =
        let obj = FmtArray([| "alpha"; "beta" |])
        formatObject obj |> shouldEqual "{Tags=[alpha; beta]}"

    [<Fact>]
    let ``formatObject formats empty array property as empty brackets``() =
        let obj = FmtArray([||])
        formatObject obj |> shouldEqual "{Tags=[]}"

    [<Fact>]
    let ``formatObject sorts properties alphabetically``() =
        // Age < Name alphabetically
        let obj = FmtMulti(30, "Bob")
        formatObject obj |> shouldEqual "{Age=30; Name=\"Bob\"}"


module ToFormUrlEncodedContentTests =

    [<Fact>]
    let ``toFormUrlEncodedContent encodes key-value pairs``() =
        task {
            use content =
                toFormUrlEncodedContent(
                    seq {
                        ("name", box "Alice")
                        ("age", box "30")
                    }
                )

            let! body = content.ReadAsStringAsync()
            body |> shouldContainText "name=Alice"
            body |> shouldContainText "age=30"
        }

    [<Fact>]
    let ``toFormUrlEncodedContent excludes null values``() =
        task {
            use content =
                toFormUrlEncodedContent(
                    seq {
                        ("present", box "yes")
                        ("missing", null)
                    }
                )

            let! body = content.ReadAsStringAsync()
            body |> shouldContainText "present=yes"
            body |> shouldNotContainText "missing"
        }

    [<Fact>]
    let ``toFormUrlEncodedContent handles empty sequence``() =
        task {
            use content = toFormUrlEncodedContent Seq.empty
            let! body = content.ReadAsStringAsync()
            body |> shouldEqual ""
        }

    [<Fact>]
    let ``toFormUrlEncodedContent formats DateTime as ISO 8601``() =
        task {
            let dt = DateTime(2024, 6, 15, 10, 30, 0, DateTimeKind.Utc)

            use content = toFormUrlEncodedContent(seq { ("ts", box dt) })

            let! body = content.ReadAsStringAsync()
            let encodedValue = body.Substring("ts=".Length)
            let decodedValue = WebUtility.UrlDecode(encodedValue)

            decodedValue |> shouldEqual(dt.ToString("O"))
        }

    [<Fact>]
    let ``toFormUrlEncodedContent formats DateTimeOffset as ISO 8601``() =
        task {
            let dto = DateTimeOffset(2024, 6, 15, 10, 30, 0, TimeSpan.Zero)

            use content = toFormUrlEncodedContent(seq { ("ts", box dto) })

            let! body = content.ReadAsStringAsync()
            let encodedValue = body.Substring("ts=".Length)
            let decodedValue = WebUtility.UrlDecode(encodedValue)

            decodedValue |> shouldEqual(dto.ToString("O"))
        }

    [<Fact>]
    let ``toFormUrlEncodedContent formats DateOnly as ISO 8601``() =
        task {
            let d = DateOnly(2025, 7, 4)
            use content = toFormUrlEncodedContent(seq { ("date", box d) })

            let! body = content.ReadAsStringAsync()
            let encodedValue = body.Substring("date=".Length)
            let decodedValue = WebUtility.UrlDecode(encodedValue)

            decodedValue |> shouldEqual "2025-07-04"
        }

    [<Fact>]
    let ``toFormUrlEncodedContent formats TimeOnly as HH:mm:ss.FFFFFFF``() =
        task {
            let t = TimeOnly(9, 5, 3, 123)
            use content = toFormUrlEncodedContent(seq { ("time", box t) })

            let! body = content.ReadAsStringAsync()
            let encodedValue = body.Substring("time=".Length)
            let decodedValue = WebUtility.UrlDecode(encodedValue)

            decodedValue |> shouldEqual "09:05:03.123"
        }

    [<Fact>]
    let ``toFormUrlEncodedContent skips values when toParam returns null``() =
        task {
            let nestedNone = box(Some(None: string option))

            use content =
                toFormUrlEncodedContent(
                    seq {
                        ("present", box "yes")
                        ("nestedNone", nestedNone)
                    }
                )

            let! body = content.ReadAsStringAsync()
            body |> shouldContainText "present=yes"
            body |> shouldNotContainText "nestedNone"
        }


module ToMultipartFormDataContentTests =

    [<Fact>]
    let ``toMultipartFormDataContent skips null values``() =
        use content =
            toMultipartFormDataContent(
                seq {
                    ("field", box "value")
                    ("empty", null)
                }
            )

        // Non-null value is present; null value is skipped (content has exactly 1 child part)
        content |> Seq.length |> shouldEqual 1

    [<Fact>]
    let ``toMultipartFormDataContent adds string values as StringContent``() =
        use content = toMultipartFormDataContent(seq { ("greeting", box "hello") })
        let part = content |> Seq.exactlyOne
        Assert.IsType<StringContent>(part) |> ignore

    [<Fact>]
    let ``toMultipartFormDataContent adds stream values with filename``() =
        use stream = new MemoryStream([| 1uy; 2uy; 3uy |])
        use content = toMultipartFormDataContent(seq { ("file", box stream) })
        content |> Seq.length |> shouldEqual 1

        let part = content |> Seq.exactlyOne
        let disposition = part.Headers.ContentDisposition

        isNull disposition |> shouldEqual false
        disposition.Name.Trim('"') |> shouldEqual "file"

        let hasFileName =
            not(String.IsNullOrWhiteSpace disposition.FileName)
            || not(String.IsNullOrWhiteSpace disposition.FileNameStar)

        hasFileName |> shouldEqual true

    [<Fact>]
    let ``toMultipartFormDataContent formats DateTime as ISO 8601``() =
        task {
            let dt = DateTime(2024, 6, 15, 10, 30, 0, DateTimeKind.Utc)
            use content = toMultipartFormDataContent(seq { ("ts", box dt) })
            let part = content |> Seq.exactlyOne
            let! body = part.ReadAsStringAsync()
            body |> shouldEqual(dt.ToString("O"))
        }

    [<Fact>]
    let ``toMultipartFormDataContent formats DateTimeOffset as ISO 8601``() =
        task {
            let dto = DateTimeOffset(2024, 6, 15, 10, 30, 0, TimeSpan.Zero)
            use content = toMultipartFormDataContent(seq { ("ts", box dto) })
            let part = content |> Seq.exactlyOne
            let! body = part.ReadAsStringAsync()
            body |> shouldEqual(dto.ToString("O"))
        }

    [<Fact>]
    let ``toMultipartFormDataContent formats DateOnly as ISO 8601``() =
        task {
            let d = DateOnly(2025, 7, 4)
            use content = toMultipartFormDataContent(seq { ("date", box d) })
            let part = content |> Seq.exactlyOne
            let! body = part.ReadAsStringAsync()
            body |> shouldEqual "2025-07-04"
        }

    [<Fact>]
    let ``toMultipartFormDataContent formats TimeOnly as HH:mm:ss.FFFFFFF``() =
        task {
            let t = TimeOnly(9, 5, 3, 123)
            use content = toMultipartFormDataContent(seq { ("time", box t) })
            let part = content |> Seq.exactlyOne
            let! body = part.ReadAsStringAsync()
            body |> shouldEqual "09:05:03.123"
        }

    [<Fact>]
    let ``toMultipartFormDataContent skips values when toParam returns null``() =
        task {
            let nestedNone = box(Some(None: string option))

            use content =
                toMultipartFormDataContent(
                    seq {
                        ("present", box "yes")
                        ("nestedNone", nestedNone)
                    }
                )

            content |> Seq.length |> shouldEqual 1
            let part = content |> Seq.exactlyOne
            let! body = part.ReadAsStringAsync()

            part.Headers.ContentDisposition.Name.Trim('"')
            |> shouldEqual "present"

            body |> shouldEqual "yes"
        }


/// Test types for getPropertyValues tests.
type PropValWithAttr(value: string) =
    [<JsonPropertyName("custom_name")>]
    member _.Value = value

type PropValWithOption(optVal: string option, required: string) =
    member _.OptVal = optVal
    member _.Required = required


module GetPropertyValuesTests =

    [<Fact>]
    let ``getPropertyValues uses JsonPropertyName attribute as serialized key``() =
        let obj = PropValWithAttr("hello")
        let result = getPropertyValues(box obj) |> Seq.toArray
        result |> Array.length |> shouldEqual 1
        let name, value = result.[0]
        name |> shouldEqual "custom_name"
        value |> shouldEqual(box "hello")

    [<Fact>]
    let ``getPropertyValues uses property name when no attribute``() =
        let obj = FmtSingle("Alice")
        let result = getPropertyValues(box obj) |> Seq.toArray
        result |> Array.length |> shouldEqual 1
        let name, _ = result.[0]
        name |> shouldEqual "Name"

    [<Fact>]
    let ``getPropertyValues unwraps Some option to inner value``() =
        let obj = PropValWithOption(Some "present", "required")
        let result = getPropertyValues(box obj) |> Seq.toArray
        let names = result |> Array.map fst
        names |> shouldContain "OptVal"
        let _, optValue = result |> Array.find(fun (n, _) -> n = "OptVal")
        optValue |> shouldEqual(box "present")

    [<Fact>]
    let ``getPropertyValues excludes None option values``() =
        let obj = PropValWithOption(None, "required")
        let result = getPropertyValues(box obj) |> Seq.toArray
        let names = result |> Array.map fst
        names |> shouldNotContain "OptVal"
        names |> shouldContain "Required"

    [<Fact>]
    let ``getPropertyValues returns empty sequence for null object``() =
        let result = getPropertyValues null |> Seq.toArray
        result |> shouldBeEmpty

    [<Fact>]
    let ``getPropertyValues cache path: second call on different instance uses cached metadata``() =
        // First call populates propNameCache for PropValWithAttr; second call reads from it.
        // Using two instances with distinct values ensures the keys still come from cached reflection.
        let first = getPropertyValues(box(PropValWithAttr("value1"))) |> Seq.toArray
        let second = getPropertyValues(box(PropValWithAttr("value2"))) |> Seq.toArray
        first |> Array.length |> shouldEqual(second |> Array.length)
        let firstName, firstValue = first.[0]
        let secondName, secondValue = second.[0]
        firstName |> shouldEqual "custom_name"
        secondName |> shouldEqual "custom_name"
        firstValue |> shouldEqual(box "value1")
        secondValue |> shouldEqual(box "value2")

/// Test type for JSON deserialization tests — a plain .NET class mirroring the generated provider types.
/// The DefinitionCompiler now wraps all non-required reference types in Option<T>.
/// This class validates that System.Text.Json correctly round-trips Option<string>.
type StringOptionClass() =
    let mutable _value: string option = None

    member _.Value
        with get () = _value
        and set (v) = _value <- v

/// Test type mirroring a generated provider type with an optional byte-array property.
type ByteArrayOptionClass() =
    let mutable _data: byte array option = None

    member _.Data
        with get () = _data
        and set (v) = _data <- v

/// Verify that the JSON serializers used by SwaggerProvider correctly map a JSON null to None
/// (and not Some(null)) for optional reference-type properties — confirming that no extra
/// sanitization is needed in the generated property setter.
module OptionDeserializationTests =
    let private optionsWithFSharpConverter =
        let opts = JsonSerializerOptions()
        opts.Converters.Add(JsonFSharpConverter())
        opts

    [<Fact>]
    let ``FSharpConverter: JSON null on string option property becomes None``() =
        let r =
            JsonSerializer.Deserialize<StringOptionClass>("""{"Value":null}""", optionsWithFSharpConverter)

        r.Value |> shouldEqual None

    [<Fact>]
    let ``FSharpConverter: JSON string on string option property becomes Some value``() =
        let r =
            JsonSerializer.Deserialize<StringOptionClass>("""{"Value":"hello"}""", optionsWithFSharpConverter)

        r.Value |> shouldEqual(Some "hello")

    [<Fact>]
    let ``FSharpConverter: missing field on string option property becomes None``() =
        let r =
            JsonSerializer.Deserialize<StringOptionClass>("""{}""", optionsWithFSharpConverter)

        r.Value |> shouldEqual None

    [<Fact>]
    let ``plain STJ: JSON null on string option property becomes None``() =
        let r = JsonSerializer.Deserialize<StringOptionClass>("""{"Value":null}""")
        r.Value |> shouldEqual None

    [<Fact>]
    let ``plain STJ: JSON string on string option property becomes Some value``() =
        let r = JsonSerializer.Deserialize<StringOptionClass>("""{"Value":"hello"}""")
        r.Value |> shouldEqual(Some "hello")

    [<Fact>]
    let ``FSharpConverter: JSON null on byte array option property becomes None``() =
        let r =
            JsonSerializer.Deserialize<ByteArrayOptionClass>("""{"Data":null}""", optionsWithFSharpConverter)

        r.Data |> shouldEqual None

    [<Fact>]
    let ``FSharpConverter: JSON base64 on byte array option property becomes Some value``() =
        let r =
            JsonSerializer.Deserialize<ByteArrayOptionClass>("""{"Data":"AQID"}""", optionsWithFSharpConverter)

        r.Data |> shouldEqual(Some [| 1uy; 2uy; 3uy |])

    [<Fact>]
    let ``FSharpConverter: missing field on byte array option property becomes None``() =
        let r =
            JsonSerializer.Deserialize<ByteArrayOptionClass>("""{}""", optionsWithFSharpConverter)

        r.Data |> shouldEqual None
