// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SwaggerProvider")>]
[<assembly: AssemblyProductAttribute("SwaggerProvider")>]
[<assembly: AssemblyDescriptionAttribute("F# Type Provider for Swagger & Open API")>]
[<assembly: AssemblyVersionAttribute("1.0.2")>]
[<assembly: AssemblyFileVersionAttribute("1.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SwaggerProvider"
    let [<Literal>] AssemblyProduct = "SwaggerProvider"
    let [<Literal>] AssemblyDescription = "F# Type Provider for Swagger & Open API"
    let [<Literal>] AssemblyVersion = "1.0.2"
    let [<Literal>] AssemblyFileVersion = "1.0.2"
